version: '3.8'

services:
    app:
        build: .
        container_name: manajemen_inventory_app
        ports:
            - '3000:3000'
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: manajemen_inventory_db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ikhwan123
            POSTGRES_DB: postgres
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
